apiVersion: v1
kind: Service
metadata:
  name: pingdataconsole-service
  labels:
    app: pingdataconsole
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: pingdataconsole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdataconsole-deployment
  labels:
    app: pingdataconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdataconsole
  template:
    metadata:
      name: pingdataconsole
      labels:
        app: pingdataconsole
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
