apiVersion: v1
kind: Service
metadata:
  name: pingdirectory
spec:
  ports:
    - port: 636
      name: ldaps
    - port: 389
      name: ldap
  clusterIP: None
  selector:
    app: pingdirectory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
  labels:
      app: pingdirectory
spec:
  serviceName: pingdirectory
  replicas: 1
  selector:
    matchLabels:
      app: pingdirectory
  template:
    metadata:
      labels:
        app: pingdirectory
    spec:
      containers:
      - name: ds
        image: pingidentity/pingdirectory:edge
        imagePullPolicy: Always
        ports:
        - containerPort: 636
        - containerPort: 443
        - containerPort: 389
        resources:
          requests:
            memory: "4Gi"
            cpu: "0"
          limits:
            memory: "4Gi"
            cpu: "0"
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "simple-sync/pingdirectory"
        - name: ENCRYPTION_PASSWORD_FILE
          value: "/opt/staging/pwd"
        envFrom:
        - secretRef:
            name: devops-secret
        readinessProbe:
          exec:
            command: 
              - /bin/sh
              - -c
              - /opt/liveness.sh

---

apiVersion: v1
kind: Service
metadata:
  name: pingdatasync
  labels:
    app: pingdatasync
spec:
  ports:
    - port: 636
      name: ldaps
    - port: 443
      name: https
  selector:
    app: pingdatasync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdatasync
  labels:
    app: pingdatasync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdatasync
  template:
    metadata:
      name: pingdatasync
      labels:
        app: pingdatasync
    spec:
      containers:
      - name: pingdatasync
        image: pingidentity/pingdatasync:edge
        ports:
        - containerPort: 636
        - containerPort: 443
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "simple-sync/pingdatasync"
        envFrom:
        - secretRef:
            name: devops-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pingdataconsole-service
  labels:
    app: pingdataconsole
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: pingdataconsole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdataconsole-deployment
  labels:
    app: pingdataconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdataconsole
  template:
    metadata:
      name: pingdataconsole
      labels:
        app: pingdataconsole
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
