apiVersion: v1
kind: Service
metadata:
  name: pingdatagovernance
  labels:
    app: pingdatagovernance
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: pingdatagovernance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdatagovernance
  labels:
    app: pingdatagovernance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdatagovernance
  template:
    metadata:
      name: pingdatagovernance
      labels:
        app: pingdatagovernance
    spec:
      containers:
      - name: pingdatagovernance
        image: pingidentity/pingdatagovernance:edge
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "getting-started/pingdatagovernance"
        envFrom:
        - secretRef:
            name: devops-secret
            optional: true
